forge "http://forge.puppetlabs.com"

mod 'java',
     :git => 'https://github.com/puppetlabs/puppetlabs-java.git'

# mod 'ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'
#

mod 'apt',
   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
   :ref => 'feature/master/dans_refactor'

mod 'tomcat6',
	:git => 'https://github.com/intere/puppet-tomcat6.git'